version: '3.7'

services:
  app:
    build:
      context: .
      # target: development
    volumes:
      - .:/src
      - /node_modules
    ports:
      - 4000:3000
    command: yarn start

    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cofrinho
      # POSTGRES_PASSWORD: ${DB_PASSWORD}
      # POSTGRES_USER: ${DB_USERNAME}
      # POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
