version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      # target: development
    volumes:
      - .:/src
      - /node_modules
    ports:
      - 4000:3000
    command: yarn start:dev
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cofrinho
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
